baseURL = "https://greenclub.vercel.app/"
title = "Green Horizons Project"
theme = "Green Horizons Project Website"
languageCode = "en-ca"
menu = [
  { name = "main", url = "/" },
  { name = "about", url = "/about/" },
  { name = "event", url = "/events/" },
  { name = "join", url = "/join/" },
  { name = "contact", url = "/contact/" }
]
